### PR TITLE
Fix scorecard typos

### PR DESCRIPTION
**Pull request by johnwalicki**
Signed-off-by: John Walicki <johnwalicki@gmail.com>

Fix typos and grammar on the scorecard cards

### CODE REVIEW

**Comment by dceejay** [comment]
Thanks John

**Comment by johnwalicki** [comment]
@dceejay - Thanks for merging my edits.
I don't see them live on the flows.nodered.org website yet.
Is there a process that needs to be kicked off to rebuild the website?

**Comment by knolleary** [comment]
@johnwalicki yes - need to merge to the `production` branch. Will do that tonight

**Comment by johnwalicki** [comment]
@knolleary  - Maybe a good update to sweep into the flows.nodered.org website before the weekend? Call it done.

**Comment by knolleary** [comment]
@johnwalicki thanks for the nudge. Deploy to production underway

**Comment by dceejay** [comment]
apologies - I didn't realise there was an extra step for the library.

**Comment by johnwalicki** [comment]
Refreshed site looks much better without a few dozen typos. Re-reading, I missed one `pacakge` typo in _P04.html - but that will be for another day.

**Pull request merged**
